apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Values.storeId }}
  labels:
    app: mysql
    store-id: {{ .Values.storeId }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mysql.persistence.storageClass }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | quote }}