apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.storeId }}
  labels:
    app: mysql
    store-id: {{ .Values.storeId }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword }}
  mysql-password: {{ .Values.mysql.password }}
  mysql-user: {{ .Values.mysql.user }}
  mysql-database: {{ .Values.mysql.database }}