apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: {{ .Values.storeId }}
  labels:
    app: wordpress
    store-id: {{ .Values.storeId }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: wordpress
    store-id: {{ .Values.storeId }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: http